#!/bin/bash

# Taskwarrior Quick Reference
# ============================

echo "📋 TASKWARRIOR QUICK REFERENCE"
echo "=============================="
echo ""
echo "BASIC COMMANDS:"
echo "  task add <description>           - Add a new task"
echo "  task list                        - Show all pending tasks"
echo "  task <id> done                   - Complete a task"
echo "  task <id> delete                 - Delete a task"
echo "  task <id> modify <changes>       - Modify a task"
echo ""
echo "PRIORITY & PROJECTS:"
echo "  task add priority:H <desc>       - Add high priority task (H/M/L)"
echo "  task add project:work <desc>     - Add task to project"
echo "  task add +tag1 +tag2 <desc>      - Add task with tags"
echo ""
echo "RECURRING TASKS:"
echo "  task add recur:daily <desc>      - Daily recurring task"
echo "  task add recur:weekly <desc>     - Weekly recurring task"
echo "  task add recur:monthly <desc>    - Monthly recurring task"
echo ""
echo "DUE DATES:"
echo "  task add due:today <desc>        - Due today"
echo "  task add due:tomorrow <desc>     - Due tomorrow"
echo "  task add due:eow <desc>          - Due end of week"
echo "  task add due:2025-08-30 <desc>   - Due specific date"
echo ""
echo "FILTERING & REPORTS:"
echo "  task project:learning            - Show tasks in learning project"
echo "  task +AI                         - Show tasks with AI tag"
echo "  task priority:H                  - Show high priority tasks"
echo "  task due:today                   - Show tasks due today"
echo "  task burndown                    - Show burndown chart"
echo "  task calendar                    - Show calendar view"
echo ""
echo "CURRENT TASKS:"
echo "==============="
task list